# NumPy

## `ndarray`

In [1]:
import numpy as np

The main object of NumPy is the _homogeneous multidimensional array_, `ndarray`. It has dimensions, called _axes_. The number of axes is called _rank_.`

In [2]:
a = np.array([[1., 2., 1.],
              [4., 3., 2.]])

Attributes:

In [5]:
a.ndim  # rank

2

In [4]:
a.shape  # axes tuple

(2, 3)

In [7]:
a.size  # number of elements (product of shape elements)

6

In [8]:
a.dtype  # all elements are the same type

dtype('float64')

In [9]:
a.itemsize  # element size in bytes

8

In [10]:
a.data  # memory buffer

***Example 1***

In [12]:
a = np.arange(15).reshape(3, 5)

In [13]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
a.shape

(3, 5)

In [15]:
type(a)

numpy.ndarray

In [18]:
a.dtype

dtype('int64')

In [19]:
a.itemsize

8

***Example 2***

In [171]:
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [173]:
t.shape

(3, 3, 2, 1)

In [174]:
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

## Creation

**`np.array()`**

`array` transforms a single sequence into a 1D array, a sequence of sequences into a 2D array, a sequence of sequences of sequences into 3D arrays, etc.

In [20]:
c = np.array([5, 6, 7])

In [21]:
c.shape  # A 1-dimensional arrays always shows the number of elements in first position

(3,)

In [22]:
c

array([5, 6, 7])

In [33]:
d = np.array([(1.3, 4.5, 6), (3, 0, 9)])

In [34]:
d

array([[ 1.3,  4.5,  6. ],
       [ 3. ,  0. ,  9. ]])

In [35]:
d.shape

(2, 3)

In [36]:
e = np.array([[1,2],[4,5]], dtype=complex)  # Specify element type explicitly

In [37]:
e

array([[ 1.+0.j,  2.+0.j],
       [ 4.+0.j,  5.+0.j]])

**`np.zeros`, `np.ones`, `np.empty`**

Placeholder elements. `zeros`, `ones`, and `empty` all take a tuple argument for shape. Element type can be specified with `dtype=`.

In [38]:
z = np.zeros( (5, 6) )

In [39]:
z

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [41]:
y = np.ones( (2, 4), dtype=np.float64)

In [42]:
y

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [43]:
xx = np.empty( (7, 8) )

In [44]:
xx

array([[ -3.10503618e+231,  -3.10503618e+231,   2.13051151e-314,
          1.48219694e-323,   6.86294615e+302,   2.13354440e-314,
          2.14744528e-314,   1.51988454e+001],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000,   0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
         -8.33010741e-253,   2.13354430e-314,   2.13134418e-314,
          1.65154049e+109,   2.13354433e-314],
       [  2.13134420e-314,  -2.63484523e-137,   2.13354181e-314,
          2.13139412e-314,   2.16726225e-314,   0.00000000e+000,
          0.00000000e+000,  -4.16398299e+147],
       [  2.13354443e-314,   2.13134418e-314,   7.20319084e-171,
          2.13354437e-314,   2.13134418e-314,   4.02852366e-186,
          2.13354427e-314,   2.13134418e-314],
       [ -4.66095077e+273,   2.13264889e-314,   2.14947569e-314,
          2.16655285e-314,   0.00000000e+000,   0.

**`arange`, `linspace`**

Sequences of numbers, like Python `range`.

In [45]:
n = np.arange(3, 13, 5)

In [46]:
n

array([3, 8])

In [50]:
m = np.arange(2, 13, .2).reshape(5, 11)  # Accepts floating point elements, but unpredictable number of elements

In [51]:
m

array([[  2. ,   2.2,   2.4,   2.6,   2.8,   3. ,   3.2,   3.4,   3.6,
          3.8,   4. ],
       [  4.2,   4.4,   4.6,   4.8,   5. ,   5.2,   5.4,   5.6,   5.8,
          6. ,   6.2],
       [  6.4,   6.6,   6.8,   7. ,   7.2,   7.4,   7.6,   7.8,   8. ,
          8.2,   8.4],
       [  8.6,   8.8,   9. ,   9.2,   9.4,   9.6,   9.8,  10. ,  10.2,
         10.4,  10.6],
       [ 10.8,  11. ,  11.2,  11.4,  11.6,  11.8,  12. ,  12.2,  12.4,
         12.6,  12.8]])

In [52]:
p = np.linspace(2, 13, 55)  # Third argument is number of elements, instead of a step (better for floats)

In [53]:
p

array([  2.        ,   2.2037037 ,   2.40740741,   2.61111111,
         2.81481481,   3.01851852,   3.22222222,   3.42592593,
         3.62962963,   3.83333333,   4.03703704,   4.24074074,
         4.44444444,   4.64814815,   4.85185185,   5.05555556,
         5.25925926,   5.46296296,   5.66666667,   5.87037037,
         6.07407407,   6.27777778,   6.48148148,   6.68518519,
         6.88888889,   7.09259259,   7.2962963 ,   7.5       ,
         7.7037037 ,   7.90740741,   8.11111111,   8.31481481,
         8.51851852,   8.72222222,   8.92592593,   9.12962963,
         9.33333333,   9.53703704,   9.74074074,   9.94444444,
        10.14814815,  10.35185185,  10.55555556,  10.75925926,
        10.96296296,  11.16666667,  11.37037037,  11.57407407,
        11.77777778,  11.98148148,  12.18518519,  12.38888889,
        12.59259259,  12.7962963 ,  13.        ])

In [54]:
p = p.reshape(5, 11)

In [55]:
p

array([[  2.        ,   2.2037037 ,   2.40740741,   2.61111111,
          2.81481481,   3.01851852,   3.22222222,   3.42592593,
          3.62962963,   3.83333333,   4.03703704],
       [  4.24074074,   4.44444444,   4.64814815,   4.85185185,
          5.05555556,   5.25925926,   5.46296296,   5.66666667,
          5.87037037,   6.07407407,   6.27777778],
       [  6.48148148,   6.68518519,   6.88888889,   7.09259259,
          7.2962963 ,   7.5       ,   7.7037037 ,   7.90740741,
          8.11111111,   8.31481481,   8.51851852],
       [  8.72222222,   8.92592593,   9.12962963,   9.33333333,
          9.53703704,   9.74074074,   9.94444444,  10.14814815,
         10.35185185,  10.55555556,  10.75925926],
       [ 10.96296296,  11.16666667,  11.37037037,  11.57407407,
         11.77777778,  11.98148148,  12.18518519,  12.38888889,
         12.59259259,  12.7962963 ,  13.        ]])

In [56]:
q = np.linspace(0, 2*np.pi, 100)

In [57]:
f = np.sin(q)

In [58]:
f

array([  0.00000000e+00,   6.34239197e-02,   1.26592454e-01,
         1.89251244e-01,   2.51147987e-01,   3.12033446e-01,
         3.71662456e-01,   4.29794912e-01,   4.86196736e-01,
         5.40640817e-01,   5.92907929e-01,   6.42787610e-01,
         6.90079011e-01,   7.34591709e-01,   7.76146464e-01,
         8.14575952e-01,   8.49725430e-01,   8.81453363e-01,
         9.09631995e-01,   9.34147860e-01,   9.54902241e-01,
         9.71811568e-01,   9.84807753e-01,   9.93838464e-01,
         9.98867339e-01,   9.99874128e-01,   9.96854776e-01,
         9.89821442e-01,   9.78802446e-01,   9.63842159e-01,
         9.45000819e-01,   9.22354294e-01,   8.95993774e-01,
         8.66025404e-01,   8.32569855e-01,   7.95761841e-01,
         7.55749574e-01,   7.12694171e-01,   6.66769001e-01,
         6.18158986e-01,   5.67059864e-01,   5.13677392e-01,
         4.58226522e-01,   4.00930535e-01,   3.42020143e-01,
         2.81732557e-01,   2.20310533e-01,   1.58001396e-01,
         9.50560433e-02,

## Printing

Print of NumPy arrays:
- The _**last** axis_ is printed _from left to right_.
- The _second to last axis_ is printed _from top to bottom_.
- The rest are also printed _from top to bottom, with slices separated by empty lines_.

In [59]:
g = np.arange(9)  # This is the LAST axis

In [60]:
g

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
g2 = np.arange(10).reshape(2, 5)

In [62]:
g2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
g3 = np.arange(45).reshape(3, 5, 3)

In [64]:
g3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]],

       [[15, 16, 17],
        [18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38],
        [39, 40, 41],
        [42, 43, 44]]])

In [65]:
gbig = np.arange(10000).reshape(100,100)

In [66]:
gbig

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ..., 
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

When the array is big, to print the whole array instead of corners only, use `np.set_printoptions(threshold='nan'`).

## Basic Operations

Basic operations are _elementwise_.

In [67]:
a0 = np.array([10, 20, 30, 40])

In [69]:
a1 = np.arange(4)

In [70]:
aminus = a0-a1

In [71]:
apow = a1**7

In [72]:
apow

array([   0,    1,  128, 2187])

In [73]:
10 * np.sin(a) 

array([[ 0.        ,  8.41470985,  9.09297427,  1.41120008, -7.56802495],
       [-9.58924275, -2.79415498,  6.56986599,  9.89358247,  4.12118485],
       [-5.44021111, -9.99990207, -5.36572918,  4.20167037,  9.90607356]])

In [74]:
a0 > 19

array([False,  True,  True,  True], dtype=bool)

**Operator `*` vs `np.dot()`**

Operator `*` in NumPy is _elementwise_ multiplication. Matrix multiplication is performed with `np.dot()`.

In [75]:
a0 * a1

array([  0,  20,  60, 120])

In [78]:
a0t = a0[:,None]

In [79]:
a0t

array([[10],
       [20],
       [30],
       [40]])

In [81]:
adota = a0.dot(a0t)

In [82]:
adota

array([3000])

In [83]:
adota.shape  # Note: This is a (1,) array, not a scalar

(1,)

In [94]:
a0.dot(a0)  # This IS a scalar!!!

3000

In [170]:
a0.dot(a0).shape  # A scalar has no/empty/zero dimensions

()

**`np.dot(a, b)`**

The dot product is:
- The _inner product_ of vectors (1D arrays)
- The _matrix product_ for 2D matrices
- The _sum product of the **last** axis of **a** and the **second-to-last** axis of **b**_ (which is a generalization of the 2D case

```python
dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
```

Documentation [link](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.dot.html#numpy.dot).

In [96]:
a0t.dot(a0)  # Now the ValueError message below makes sense

ValueError: shapes (4,1) and (4,) not aligned: 1 (dim 1) != 4 (dim 0)

In [85]:
a0.shape

(4,)

In [86]:
a0t.shape

(4, 1)

In [90]:
a0, a0t

(array([10, 20, 30, 40]), array([[10],
        [20],
        [30],
        [40]]))

In [91]:
ata = a0*a0t  # Elementwise!

In [92]:
ata  # A (4,) array multiplied elementwise with a (4, 1) array for a (4, 4) array

array([[ 100,  200,  300,  400],
       [ 200,  400,  600,  800],
       [ 300,  600,  900, 1200],
       [ 400,  800, 1200, 1600]])

In [93]:
ata.shape

(4, 4)

In [88]:
a0t*a0  # Order doesn't matter for elementwise multiplication!

array([[ 100,  200,  300,  400],
       [ 200,  400,  600,  800],
       [ 300,  600,  900, 1200],
       [ 400,  800, 1200, 1600]])

In [97]:
A = np.array([[5., 6.], [4., 0.]])
B = np.eye(2)

In [98]:
A * B  # Elementwise

array([[ 5.,  0.],
       [ 0.,  0.]])

In [99]:
A.dot(B)

array([[ 5.,  6.],
       [ 4.,  0.]])

In [100]:
B.dot(A)

array([[ 5.,  6.],
       [ 4.,  0.]])

In [101]:
C = np.arange(6).reshape(2, 3)

In [102]:
C

array([[0, 1, 2],
       [3, 4, 5]])

In [103]:
C.dot(B)  # This won't work

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [104]:
C.T  # Transpose C

array([[0, 3],
       [1, 4],
       [2, 5]])

In [105]:
C.T.dot(B)

array([[ 0.,  3.],
       [ 1.,  4.],
       [ 2.,  5.]])

In [106]:
B.dot(C)  # This should work (Note: This is only equal the transpose of above because B is an identity matrix!)

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [107]:
B == np.eye(2)

array([[ True,  True],
       [ True,  True]], dtype=bool)

In [110]:
A.dot(C) == C.T.dot(A).T  # In general A•B ≠ B•A, nor A•B ≠ (B^•A)^ (where B^ is the transpose of B, etc.)

array([[False, False, False],
       [ True, False, False]], dtype=bool)

**`np.dot()` vs `np.matmul()`**

`np.dot()` and `np.matmul()` are equivalent for 1D and 2D arrays, but **differ** for higher-dimensional arrays. 

`matmul` differs from `dot` in two important ways:

- Multiplication by scalars is not allowed.
- Stacks of matrices are broadcast together as if the matrices were elements.


Documentation [link](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.matmul.html). On [SO](https://stackoverflow.com/a/34142617/6562147).

In [238]:
by0 = np.arange(4).reshape(2, 2)

In [239]:
by0

array([[0, 1],
       [2, 3]])

In [240]:
by1 = np.arange(4).reshape(2, 2)*5

In [241]:
by1

array([[ 0,  5],
       [10, 15]])

In [242]:
by0.dot(by1)

array([[10, 15],
       [30, 55]])

In [243]:
np.matmul(by0, by1)

array([[10, 15],
       [30, 55]])

In [244]:
shape0 = np.arange(6).reshape(2, 3)

In [245]:
shape0

array([[0, 1, 2],
       [3, 4, 5]])

In [246]:
shape1 = 3*np.arange(6).reshape(3, 2)

In [247]:
shape1

array([[ 0,  3],
       [ 6,  9],
       [12, 15]])

In [251]:
shape0.dot(shape1), shape1.dot(shape0)

(array([[ 30,  39],
        [ 84, 120]]), array([[ 9, 12, 15],
        [27, 42, 57],
        [45, 72, 99]]))

In [250]:
np.matmul(shape0, shape1), np.matmul(shape1, shape0)

(array([[ 30,  39],
        [ 84, 120]]), array([[ 9, 12, 15],
        [27, 42, 57],
        [45, 72, 99]]))

**Binary Operators**

Applied elementwise. **Note:** _Upcasting_ applies for _compound assignment_!

In [111]:
C = np.ones( (2, 3), dtype=int)

In [112]:
C

array([[1, 1, 1],
       [1, 1, 1]])

In [113]:
D = np.random.random( (2, 3) )

In [114]:
D

array([[ 0.51760412,  0.9860861 ,  0.94333679],
       [ 0.7851441 ,  0.02112656,  0.53495299]])

In [115]:
C += D  # D won't be cast automatically to int (downcasting)

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [116]:
D += C  # Upcasting

In [117]:
D

array([[ 1.51760412,  1.9860861 ,  1.94333679],
       [ 1.7851441 ,  1.02112656,  1.53495299]])

In [118]:
C + D

array([[ 2.51760412,  2.9860861 ,  2.94333679],
       [ 2.7851441 ,  2.02112656,  2.53495299]])

**A Useful Trick for Reusing an Array**

In [237]:
C *= 0  # Zero out an array to reuse in code, by elementwise multiply by 0 :D

In [236]:
C

array([[0, 0, 0],
       [0, 0, 0]])

**Unary Operations**

Applied to the elements of the array regardless of its shape.

In [119]:
E = np.random.random( (7, 9) )

In [121]:
np.sum(E), np.min(E), np.max(E)

(32.335245623597906, 0.029958031700565546, 0.98269300003978233)

**Specifying the Axis for Operations**

Axes are counted from 0.

In [122]:
np.sum(D, axis=0)  # Column-wise sum

array([ 3.30274822,  3.00721265,  3.47828978])

In [123]:
np.sum(D, axis=1)  # Row-wise sum

array([ 5.44702701,  4.34122365])

In [124]:
D.cumsum(axis=1)  # Row-wise cumulative sum

array([[ 1.51760412,  3.50369022,  5.44702701],
       [ 1.7851441 ,  2.80627066,  4.34122365]])

**Universal Function**

Applied _elementwise_.

In [125]:
np.add(C, D)

array([[ 2.51760412,  2.9860861 ,  2.94333679],
       [ 2.7851441 ,  2.02112656,  2.53495299]])

In [126]:
np.exp(C)

array([[ 2.71828183,  2.71828183,  2.71828183],
       [ 2.71828183,  2.71828183,  2.71828183]])

In [127]:
np.sqrt(D)

array([[ 1.23191076,  1.40928567,  1.39403615],
       [ 1.33609285,  1.01050807,  1.2389322 ]])

## Indexing, Slicing, and Iteration

1D arrays can be _indexed, sliced,_ and _iterated_ over like lists.

In [128]:
F = np.arange(100)**1.5

In [129]:
F

array([   0.        ,    1.        ,    2.82842712,    5.19615242,
          8.        ,   11.18033989,   14.69693846,   18.52025918,
         22.627417  ,   27.        ,   31.6227766 ,   36.48287269,
         41.56921938,   46.87216658,   52.38320341,   58.09475019,
         64.        ,   70.09279564,   76.36753237,   82.81907993,
         89.4427191 ,   96.23408959,  103.18914672,  110.30412504,
        117.57550765,  125.        ,  132.57450735,  140.29611541,
        148.16207342,  156.16977941,  164.31676725,  172.60069525,
        181.01933598,  189.57056734,  198.25236442,  207.06279241,
        216.        ,  225.06221362,  234.24773211,  243.55492194,
        252.98221281,  262.52809373,  272.19110933,  281.96985654,
        291.86298155,  301.86917696,  311.98717922,  322.21576622,
        332.55375505,  343.        ,  353.55339059,  364.21284986,
        374.97733265,  385.84582413,  396.81733833,  407.89091679,
        419.06562732,  430.34056281,  441.71484014,  453.18759

In [130]:
F[41]

262.52809373474679

In [131]:
F[20:41]

array([  89.4427191 ,   96.23408959,  103.18914672,  110.30412504,
        117.57550765,  125.        ,  132.57450735,  140.29611541,
        148.16207342,  156.16977941,  164.31676725,  172.60069525,
        181.01933598,  189.57056734,  198.25236442,  207.06279241,
        216.        ,  225.06221362,  234.24773211,  243.55492194,
        252.98221281])

In [134]:
F[:60:7] = -1024

In [135]:
F

array([ -1.02400000e+03,   1.00000000e+00,   2.82842712e+00,
         5.19615242e+00,   8.00000000e+00,   1.11803399e+01,
         1.46969385e+01,  -1.02400000e+03,   2.26274170e+01,
         2.70000000e+01,   3.16227766e+01,   3.64828727e+01,
         4.15692194e+01,   4.68721666e+01,  -1.02400000e+03,
         5.80947502e+01,   6.40000000e+01,   7.00927956e+01,
         7.63675324e+01,   8.28190799e+01,   8.94427191e+01,
        -1.02400000e+03,   1.03189147e+02,   1.10304125e+02,
         1.17575508e+02,   1.25000000e+02,   1.32574507e+02,
         1.40296115e+02,  -1.02400000e+03,   1.56169779e+02,
         1.64316767e+02,   1.72600695e+02,   1.81019336e+02,
         1.89570567e+02,   1.98252364e+02,  -1.02400000e+03,
         2.16000000e+02,   2.25062214e+02,   2.34247732e+02,
         2.43554922e+02,   2.52982213e+02,   2.62528094e+02,
        -1.02400000e+03,   2.81969857e+02,   2.91862982e+02,
         3.01869177e+02,   3.11987179e+02,   3.22215766e+02,
         3.32553755e+02,

In [138]:
for f in F[:10]:
    print(f**(1/3.))

nan
1.0
1.41421356237
1.73205080757
2.0
2.2360679775
2.44948974278
nan
2.82842712475
3.0


/Applications/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in double_scalars
  from ipykernel import kernelapp as app


_Mutlidimensional_ arrays have one index per axis, collected in a tuple.

In [151]:
H = np.fromfunction(lambda x,y:10*x+y, (5, 4), dtype=int)

In [152]:
H.shape

(5, 4)

In [153]:
H

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [154]:
H[3, 2]

32

In [155]:
H[2:4, 3]

array([23, 33])

In [156]:
H[:, 3]

array([ 3, 13, 23, 33, 43])

In [157]:
H[1:3, :]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

Missing indices are considered _complete slices (as in `:`)_.

In [158]:
H[-1]  # Equivalent to H[-1, :]

array([40, 41, 42, 43])

In [159]:
H[-1, ...]  # An alternative way to acheive the same things

array([40, 41, 42, 43])

In [160]:
J = np.arange(2*3*5).reshape(2, 3, 5)

In [161]:
J[1, 2, ...]

array([25, 26, 27, 28, 29])

In [164]:
J[1, ...]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [165]:
J[..., 4]

array([[ 4,  9, 14],
       [19, 24, 29]])

Iteration over _multidimensiona_ arrays is performed over the _**first** axes ("rows")_.

In [166]:
for row in J:
    print(row)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


To iterate over all the elements of the array, _flatten_ the array with `numpy.flat`.

In [167]:
for e in J.flat:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


## Shape Manipulation

### `np.reshape`

`np.reshape` does not change the original array. Return a new array.

In [175]:
K = np.array([1, 2, 5, 7])

In [176]:
K.shape

(4,)

In [177]:
K

array([1, 2, 5, 7])

In [178]:
KR = K.reshape(1, 4)

In [179]:
KR.shape

(1, 4)

In [180]:
KR  # Notice the extra square brackets, adding the second dimension (axis 1)

array([[1, 2, 5, 7]])

In [181]:
L = np.arange(4*6).reshape(4, 6)

In [182]:
L

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [183]:
L.reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [187]:
L.ravel()  # Flatten w/ C-style ordering (i.e. rightmost index changes the fastest, so [0,0] then [0,1], etc)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [186]:
L.T  # Transpose (NOTE: Same shape as, but very different values from L.reshape(6, 4)!!!)

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [188]:
L.reshape(3, -1)  # -1 indicates to calculate the rest of the arguments

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

## Stacking Arrays

### `np.vstack()`, `np.hstack()`, `np.column_stack()`, `np.concatenate()`

In [197]:
ra = np.floor( 10 * np.random.random( (2, 2) ) )
rb = np.floor( 10 * np.random.random( (2, 2) ) )

In [198]:
ra

array([[ 4.,  8.],
       [ 3.,  9.]])

In [199]:
rb

array([[ 1.,  1.],
       [ 9.,  9.]])

In [201]:
np.vstack( (ra, rb) )

array([[ 4.,  8.],
       [ 3.,  9.],
       [ 1.,  1.],
       [ 9.,  9.]])

In [202]:
np.hstack( (rb, ra) )

array([[ 1.,  1.,  4.,  8.],
       [ 9.,  9.,  3.,  9.]])

In [204]:
np.column_stack( (ra, rb) )   # For 2D arrays, equivalent to hstack()

array([[ 4.,  8.,  1.,  1.],
       [ 3.,  9.,  9.,  9.]])

In [206]:
np.column_stack( (np.array([3,4,6,8]), np.random.random(4)) )  # For vectors, it stacks them as columns in a 2D array

array([[ 3.        ,  0.13429577],
       [ 4.        ,  0.57469205],
       [ 6.        ,  0.20300442],
       [ 8.        ,  0.56921239]])

In [207]:
np.vstack( (np.array([3,4,6,8]), np.random.random(4)) )  # For vectors, vstack() behaves differently

array([[ 3.        ,  4.        ,  6.        ,  8.        ],
       [ 0.64198522,  0.56386008,  0.00966737,  0.037262  ]])

In [210]:
np.vstack( (np.array([3,4,6,8])[:,np.newaxis], np.random.random(4)[:,np.newaxis]) )  # To stack vertically, reshape with np.newaxis

array([[ 3.        ],
       [ 4.        ],
       [ 6.        ],
       [ 8.        ],
       [ 0.63411624],
       [ 0.55348191],
       [ 0.2383115 ],
       [ 0.35753028]])

In [220]:
v0 = np.array([3, 4, 6, 8])  # How to convert this to a column vector?

In [221]:
v0.shape  # A (row) vector has dimensions (x,). This only one dimension, with x number of elements.

(4,)

In [212]:
v0.reshape(1, 4)  # This gives us a (1, 4) array, not a column vector!!!

array([[3, 4, 6, 8]])

In [223]:
v0.reshape(4, 1)  # The column vector is (4, 1)

array([[3],
       [4],
       [6],
       [8]])

***Using `np.newaxes` or `None`***

`np.reshape(x, 1)` and `np.reshape(1, x)` can be done with a slicing trick, utilizing the `np.newaxis` object to create _an axis of **length 1**_.

Documentation [link](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#numpy.newaxis).

In [222]:
c0 = v0[:, np.newaxis]  

In [219]:
c0.shape

(4, 1)

In [224]:
c0

array([[3],
       [4],
       [6],
       [8]])

In [225]:
v0[:, None]  # None is equivalent to np.newaxis

array([[3],
       [4],
       [6],
       [8]])

In [234]:
v0[None, :]  # Equivalent to np.reshape(1, 4) (that is, from (4,) to (1, 4))

array([[3, 4, 6, 8]])

***Stacking Numbers Along an Axis with `np.r_` and `np.c_`***

The constructs `np.r_` and `np.c_` translate _slice objects_ to concatenation, along the first and second axes, respectively. They accept range arguments.

Documentation [link](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.r_.html#numpy.r_) for advanced usage. See also [`concatenate`](https://docs.scipy.org/doc/numpy-dev/reference/generated/numpy.concatenate.html#numpy.concatenate).

In [227]:
np.r_[4, 5, 6, 7, 2, 1, 3, 6]

array([4, 5, 6, 7, 2, 1, 3, 6])

In [228]:
np.r_[4:17, 19:25, 27]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22,
       23, 24, 27])

In [231]:
np.c_[5:7, 10:12]

array([[ 5, 10],
       [ 6, 11]])

In [232]:
np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]

array([[1, 2, 3, 0, 0, 4, 5, 6]])